#数据库
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=ZJ
#spring.datasource.password=admin
#spring.datasource.driver-class-name = oracle.jdbc.OracleDriver

#mybatis映射文件
#mybatis.mapper-locations=classpath*:mapper/*.xml
#mybatis.type-aliases-package=task.taskdao

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #spring data jpa
    jpa:
      show-sql: true # 默认false，在日志里显示执行的sql语句
      database: mysql
      hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    #thymeleaf 配置=HTML5
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false

#springmvc
#  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/jsp/
#mybatis映射文件
mybatis:
  mapper-locations: classpath*:mapper/*.xml

#mybatis打印sql
logging:
  level.org.springframework.web: error
  level.org.hibernate.SQL: debug
  level.org.hibernate.engine.QueryParameters: debug
  level.org.hibernate.engine.query.HQLQueryPlan: debug
  level.org.hibernate.type.descriptor.sql.BasicBinder: trace
  level.com.zerf.demo: debug